package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EquipeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEquipeAllPropertiesEquals(Equipe expected, Equipe actual) {
        assertEquipeAutoGeneratedPropertiesEquals(expected, actual);
        assertEquipeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEquipeAllUpdatablePropertiesEquals(Equipe expected, Equipe actual) {
        assertEquipeUpdatableFieldsEquals(expected, actual);
        assertEquipeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEquipeAutoGeneratedPropertiesEquals(Equipe expected, Equipe actual) {
        assertThat(actual)
            .as("Verify Equipe auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEquipeUpdatableFieldsEquals(Equipe expected, Equipe actual) {
        assertThat(actual)
            .as("Verify Equipe relevant properties")
            .satisfies(a -> assertThat(a.getNom()).as("check nom").isEqualTo(expected.getNom()))
            .satisfies(a -> assertThat(a.getPrenom()).as("check prenom").isEqualTo(expected.getPrenom()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEquipeUpdatableRelationshipsEquals(Equipe expected, Equipe actual) {
        // empty method
    }
}
