package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MaterielEnStockAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMaterielEnStockAllPropertiesEquals(MaterielEnStock expected, MaterielEnStock actual) {
        assertMaterielEnStockAutoGeneratedPropertiesEquals(expected, actual);
        assertMaterielEnStockAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMaterielEnStockAllUpdatablePropertiesEquals(MaterielEnStock expected, MaterielEnStock actual) {
        assertMaterielEnStockUpdatableFieldsEquals(expected, actual);
        assertMaterielEnStockUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMaterielEnStockAutoGeneratedPropertiesEquals(MaterielEnStock expected, MaterielEnStock actual) {
        assertThat(actual)
            .as("Verify MaterielEnStock auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMaterielEnStockUpdatableFieldsEquals(MaterielEnStock expected, MaterielEnStock actual) {
        assertThat(actual)
            .as("Verify MaterielEnStock relevant properties")
            .satisfies(a -> assertThat(a.getDateReception()).as("check dateReception").isEqualTo(expected.getDateReception()))
            .satisfies(a -> assertThat(a.getQuantite()).as("check quantite").isEqualTo(expected.getQuantite()))
            .satisfies(a -> assertThat(a.getMateriel()).as("check materiel").isEqualTo(expected.getMateriel()))
            .satisfies(a -> assertThat(a.getNoserie()).as("check noserie").isEqualTo(expected.getNoserie()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMaterielEnStockUpdatableRelationshipsEquals(MaterielEnStock expected, MaterielEnStock actual) {
        // empty method
    }
}
