package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MaterielSurLeTerrainAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMaterielSurLeTerrainAllPropertiesEquals(MaterielSurLeTerrain expected, MaterielSurLeTerrain actual) {
        assertMaterielSurLeTerrainAutoGeneratedPropertiesEquals(expected, actual);
        assertMaterielSurLeTerrainAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMaterielSurLeTerrainAllUpdatablePropertiesEquals(MaterielSurLeTerrain expected, MaterielSurLeTerrain actual) {
        assertMaterielSurLeTerrainUpdatableFieldsEquals(expected, actual);
        assertMaterielSurLeTerrainUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMaterielSurLeTerrainAutoGeneratedPropertiesEquals(MaterielSurLeTerrain expected, MaterielSurLeTerrain actual) {
        assertThat(actual)
            .as("Verify MaterielSurLeTerrain auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMaterielSurLeTerrainUpdatableFieldsEquals(MaterielSurLeTerrain expected, MaterielSurLeTerrain actual) {
        assertThat(actual)
            .as("Verify MaterielSurLeTerrain relevant properties")
            .satisfies(a -> assertThat(a.getDateAffectattion()).as("check dateAffectattion").isEqualTo(expected.getDateAffectattion()))
            .satisfies(a -> assertThat(a.getMateriel1()).as("check materiel1").isEqualTo(expected.getMateriel1()))
            .satisfies(a -> assertThat(a.getSerie1()).as("check serie1").isEqualTo(expected.getSerie1()))
            .satisfies(a -> assertThat(a.getEtat1()).as("check etat1").isEqualTo(expected.getEtat1()))
            .satisfies(a -> assertThat(a.getNombre1()).as("check nombre1").isEqualTo(expected.getNombre1()))
            .satisfies(a -> assertThat(a.getMateriel2()).as("check materiel2").isEqualTo(expected.getMateriel2()))
            .satisfies(a -> assertThat(a.getSerie2()).as("check serie2").isEqualTo(expected.getSerie2()))
            .satisfies(a -> assertThat(a.getEtat2()).as("check etat2").isEqualTo(expected.getEtat2()))
            .satisfies(a -> assertThat(a.getNombre2()).as("check nombre2").isEqualTo(expected.getNombre2()))
            .satisfies(a -> assertThat(a.getMateriel3()).as("check materiel3").isEqualTo(expected.getMateriel3()))
            .satisfies(a -> assertThat(a.getSerie3()).as("check serie3").isEqualTo(expected.getSerie3()))
            .satisfies(a -> assertThat(a.getEtat3()).as("check etat3").isEqualTo(expected.getEtat3()))
            .satisfies(a -> assertThat(a.getNombre3()).as("check nombre3").isEqualTo(expected.getNombre3()))
            .satisfies(a -> assertThat(a.getMateriel4()).as("check materiel4").isEqualTo(expected.getMateriel4()))
            .satisfies(a -> assertThat(a.getSerie4()).as("check serie4").isEqualTo(expected.getSerie4()))
            .satisfies(a -> assertThat(a.getEtat4()).as("check etat4").isEqualTo(expected.getEtat4()))
            .satisfies(a -> assertThat(a.getNombre4()).as("check nombre4").isEqualTo(expected.getNombre4()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMaterielSurLeTerrainUpdatableRelationshipsEquals(MaterielSurLeTerrain expected, MaterielSurLeTerrain actual) {
        assertThat(actual)
            .as("Verify MaterielSurLeTerrain relationships")
            .satisfies(a -> assertThat(a.getEquipe()).as("check equipe").isEqualTo(expected.getEquipe()));
    }
}
